name: Publish NPM
on:
  push:
    tags:
      - v*
jobs:
  publish:
    name: Create npm package
    runs-on: ubuntu-latest
    env:
      NPM_PACKAGE_NAME: ${{ vars.NPM_PACKAGE_NAME }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Publish package
        run: node publish.js
